export const GenericIssues = {
  G101: {
    issueText: 'issue text and then some more issue text',
    learnMoreText: 'here is some learn more text',
    issueID: '101',
    correctResponse: 'keepUp',
    issueType: 'generic',
  },
  G102: {
    issueText: 'issue text and then some more issue text',
    learnMoreText: 'here is some learn more text',
    issueID: '102',
    correctResponse: 'keepUp',
    issueType: 'generic',
  },
  G103: {
    issueText: 'issue text and then some more issue text',
    learnMoreText: 'here is some learn more text',
    issueID: '103',
    correctResponse: 'keepUp',
    issueType: 'generic',
  },
  G104: {
    issueText: 'issue text and then some more issue text',
    learnMoreText: 'here is some learn more text',
    issueID: '104',
    correctResponse: 'keepUp',
    issueType: 'generic',
  },
  G105: {
    issueText: 'issue text and then some more issue text',
    learnMoreText: 'here is some learn more text',
    issueID: '105',
    correctResponse: 'keepUp',
    issueType: 'generic',
  },
  G106: {
    issueText: 'issue text and then some more issue text',
    learnMoreText: 'here is some learn more text',
    issueID: '106',
    correctResponse: 'keepUp',
    issueType: 'generic',
  },
  G1000: {
    issueText: 'example issue text 1',
    learnMoreText: 'learn more text',
    issueID: '1',
    correctResponse: 'keepUp',
    postIssueInterstitial: "here's a post-interstitial",
    keepUpConsequences: {
      followUpID: 'F1000',
      followUpTimeDelay: 2,
      followUpPosition: null,
    },
    issueType: 'generic',
  },
  G1001: {
    issueText: 'example issue text 2',
    learnMoreText: 'learn more text',
    issueID: '2',
    correctResponse: 'keepUp',
    issueType: 'generic',
  },
  G1002: {
    interstitialOnly: "this is an interstitial that isn't attached to a card",
    issueType: 'generic',
  },
  G1003: {
    issueText: 'example issue text 3',
    learnMoreText: 'learn more text',
    issueID: '3',
    correctResponse: 'keepUp',
    preIssueInterstitial: "here's a pre-interstitial",
    issueType: 'generic',
  },
}
